### ISSUE TITLE
Fix issues preventing library from working in Wagtail 2.16

### ISSUE THREAD

**Issue by marteinn** [Frojd/wagtail-trash#11]

**Comment by polesello** [comment]
Trying to delete a page, an error is thrown (Permission denied)
"You don't have permission to access this area"

**Comment by marteinn** [comment]
Thanks for adding more details @polesello! We are continuing to investigate this issue. Will report back here when we have more updates.

**Comment by marteinn** [comment]
@polesello Fixed in https://github.com/Frojd/wagtail-trash/releases/tag/v0.2.1
