### ISSUE TITLE
500 when accessing the trash can

### ISSUE THREAD

**Issue by facorazza** [Frojd/wagtail-trash#3]
I get a 500 error code when I try to access the trash can at http://localhost/cms/wagtail_trash/trashcan/

Wagtail v2.11.2

**Comment by rinti** [comment]
Hi! Have you ran migrations? Did you get a traceback?

**Comment by facorazza** [comment]
Nope

```
Apply all migrations: admin, auth, contenttypes, cookie_consent, postgres_search, sessions, sites, taggit, tastypie, wagtail_trash, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailmedia, wagtailredirects, wagtailsearch, wagtailusers
Running migrations:
No migrations to apply.
```

**Comment by rinti** [comment]
@facorazza Could you provide the traceback from the 500 error?

**Comment by facorazza** [comment]
TemplateDoesNotExist at /cms/wagtail_trash/trashcan/
<img width="1018" alt="Screenshot 2020-11-29 at 15 35 45" src="https://user-images.githubusercontent.com/20555025/100544813-b0397b00-3258-11eb-9980-00a28d922ada.png">

**Comment by rinti** [comment]
@facorazza Thanks!

You need to add `wagtail.contrib.modeladmin` to your `INSTALLED_APPS`.

**Comment by rinti** [comment]
I've updated the readme to include a note about modeladmin in https://github.com/Frojd/wagtail-trash/commit/4269281f89732837dd90f7eec1563df1668ad0e1

**Comment by facorazza** [comment]
Awesome!
