### ISSUE TITLE
Bug: Incorrect template directory name (develop branch)

### ISSUE THREAD

**Issue by cspollar** [Frojd/wagtail-trash#4]
When using wagtail-trash (`pip install wagtail-trash`) I get the following exception after clicking the "Restore and Move" button.

```
TemplateDoesNotExist at /cms/wagtail_trash/restore_and_move/2173/
wagtail_trash/move.html
Request Method:	GET
Request URL:	http://127.0.0.1:8000/cms/wagtail_trash/restore_and_move/2173/
Django Version:	3.2.3
Exception Type:	TemplateDoesNotExist
Exception Value:	
wagtail_trash/move.html
```

# Solution

Rename [template directory](https://github.com/Frojd/wagtail-trash/tree/develop/wagtail_trash/templates) `wagtail_recycle_bin` to `wagtail_trash` as named in [views.py](https://github.com/Frojd/wagtail-trash/blob/4269281f89732837dd90f7eec1563df1668ad0e1/wagtail_trash/views.py#L77)

**Comment by rinti** [comment]
This is now fixed in 0.1.1. Thanks a lot @cspollar!
